### ISSUE TITLE
Weird Navigation Bar and TableView behind Navigation Bar.

### ISSUE THREAD

**Issue by rahulrs0029** [twostraws/Unwrap#136]
In the News tab, when the refresh controls stops refreshing, Navigation Bar stays tall and Table View is behind Navigation Bar.

<img src="https://user-images.githubusercontent.com/21116964/57971178-34dee400-79a8-11e9-8bb8-f482b82236e8.png" width=264 />

**Comment by twostraws** [comment]
Thanks for the report! I can't reproduce this – can you provide some details? Does it occur in the latest code from GitHub?

**Comment by rahulrs0029** [comment]
Yes it still occurs in the latest version.
But it doesn't occurs every time. It happens like 2 times in 5 times.
[Video Recording](https://imgur.com/1o36DZa)

**Comment by twostraws** [comment]
You're welcome to try and fix this is you want; I'm not terribly worried about it, because it seems to clear itself if you just refresh again. Honestly, news refreshing is realistically a non-feature because it's not likely anyone publishes news so often there will be new content in the app while they are using it.

**Comment by rahulrs0029** [comment]
Yeah agreed. News won’t be published too often.

So I did some search on Google regarding this issue. It said that whenever Navigation Bar is not translucent, we need to add this line of code to fix Refresh Control issues:
self.extendedLayoutIncludesOpaqueBars = true

I’ll try this tomorrow and open a PR if it fixes the issue. 😃
