### ISSUE TITLE
Keyboard not hiding in SingleSelectReviewViewController

### ISSUE THREAD

**Issue by p4vlos** [twostraws/Unwrap#27]
Cannot hide the keyboard after I click on the SyntaxTextView and the "Check" button is hidden under the keyboard

![img_4667](https://user-images.githubusercontent.com/11935187/44684639-7ce86000-aa41-11e8-8f51-723a54503919.PNG)

**Comment by ihak** [comment]
[savannakit](https://github.com/louisdh/savannakit) doesn't provide a way to make the `SyntaxTextView` readonly. 

Currently there is no other way except overriding the `TextView`'s `canBecomeFirstResponder` property and returning false. But that only makes it even worse because then `SyntaxTextView` becomes non-editable for the whole app.

They should provide `shouldBeginEditing` delegate to handle these kind of issues. I have opened an [issue](https://github.com/louisdh/savannakit/issues/19) for that.

**Comment by twostraws** [comment]
Can't we just reach into the inner text view and modify it there?
